### ISSUE TITLE
Add padding to bottom of content

### ISSUE THREAD

**Issue by rmccue** [sourcegraph/docs.sourcegraph.com#2]
Right now, the content is flush against the bottom of the window, which is a bit painful to read. It'd be great if there was a bit of padding there as well. :)

**Comment by sqs** [comment]
Thanks, will fix tonight!

**Comment by sqs** [comment]
Fixed. Will be deployed in a few hours. I also squashed history now that this repository is in use.

I'll manually close this issue when I confirm it's deployed.
